### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by bbb651** [PolyMeilex/wlprobe#38]
Hey, came here from [wayland-explorer](https://github.com/vially/wayland-explorer) while working on COSMIC support, this is really neat and useful tool!

It would be nice if this was published on crates.io, so you can install it with `cargo install wlprobe` - well you can already do `cargo install --git https://github.com/PolyMeilex/wlprobe`, but it's shorter to type and it'll use a releases by default rather than `master`. Also it seems like `version` is not property updated in `Cargo.toml` with the release tags, it's always `0.1.0`.

**Comment by PolyMeilex** [comment]
Done
